### ISSUE TITLE
Rate-limit API routes by IP

### ISSUE THREAD

**Issue by Ameobea** [Ameobea/robintrack#60]
Need to prevent overzealous bots from overloading things

**Comment by dalexj** [comment]
lmk when you work on this @Ameobea, am wondering what you will use

**Comment by Ameobea** [comment]
I'm going to do a simple impl using Redis, tied to IPs.  Thinking about having a hash for each route mapping IP address to request timings, updating it each time a route is hit, and then checking if existing request timings meet or miss some per-route threshold.

That's just my current idea, I'm open to other options

**Comment by dalexj** [comment]
we have a similar thing in a rails project at work that i could send over to you. basically records timeouts to ES within redis and checks if we get >5 within 60 seconds. would be super easy to extend to have the redis key include the request ip

**Comment by Ameobea** [comment]
That sounds pretty ideal - I'm down to work on this together after work if you want

**Comment by Ameobea** [comment]
Closed by #66
