### ISSUE TITLE
File PRN.csv in the export causes permissions issues on Windows due to reserved name

### ISSUE THREAD

**Issue by Ameobea** [Ameobea/robintrack#65]
Should probably rename to _PRN.csv or something and put info about that on the download page to help people out who use the data on Windows

**Comment by daleholborow** [comment]
This is a common problem I've encountered in a product of my own. You'll find similar issues with things called ~com etc, there are several reserved words. My solution was to prefix files with underscore etc

**Comment by pp92391** [comment]
Hi guys, I'm experiencing the same issue when extracting the data into Python. I'm a beginner in Python.

I download the Robintrack tar.gz file manually via the website. I then try to extract the files using tarfile in Python:
import tarfile
tf = tarfile.open(fname)
tf.extractall()

But I get the error: FileNotFoundError: [Errno 2] No such file or directory: '.\\tmp\\popularity_export\\PRN.csv'

Any solution to overcome this without manually extracting the files out of Python first?

Thanks very much for any help

**Comment by pp92391** [comment]
Thanks for the reply dalexj - how do I use this write_csv_file script (or all the popularity_history_exporter script in general) to export the tar.gz file? Sorry if this is a basic question.

I have the path name of my tar.gz file - where do I go from there to just extract all that data into Python?

**Comment by Ameobea** [comment]
The changes to prefix file names that are reserved on Windows has been pushed and the current archive available for download shouldn't have any issues on Windows.

@pp92391 you don't need to run the script yourself, it runs automatically and is used to produce the archive available for download on the Robintrack website.

**Comment by pp92391** [comment]
> The changes to prefix file names that are reserved on Windows has been pushed and the current archive available for download shouldn't have any issues on Windows.
> 
> @pp92391 you don't need to run the script yourself, it runs automatically and is used to produce the archive available for download on the Robintrack website.

Thank you very much Ameobea, works very well now. Appreciate the help!
