### ISSUE TITLE
Server seems to be down

### ISSUE THREAD

**Issue by Tsopic** [Ameobea/robintrack#70]
Sorry for creating issue instead of using the feedback link.  Feedback link did not work.

Seems that API is down and returning 503, hope this gets resolved soon.

**Comment by Ameobea** [comment]
No need to apologize, I appreciate it.  The server rebooted unexpectedly while I was asleep; I don't know why but if it happens again I'll work on setting everything up to automatically start on server boot.  Thanks again for letting me know.
