### ISSUE TITLE
Data Download not working on site

### ISSUE THREAD

**Issue by tadbooch** [Ameobea/robintrack#89]
Hi,
Thanks for this awesome tool, gives good insight into what others are thinking.
The data download link (https://robintrack-data.ameo.design/robintrack-popularity-history.tar.xz) on site doesn't seem to be working correctly. When I click on it, a file is downloaded which has two empty folders and practically zero file size.
Do you know if there is any issue with it?
Thank you in advance,

**Comment by babeljeff** [comment]
Having the same issue...  thanks!

**Comment by Ameobea** [comment]
I've fixed the data export script and switched it back to tar.gz format.  The link on the data export page is updated and the export should properly run nightly as it has in the past.  If any other issues come up, please let me know!

**Comment by tadbooch** [comment]
Thank you for looking into this.

**Comment by tadbooch** [comment]
Hello, do you think your export worked fine last night? When I look at file now, last data point is as of 7/18.
At what time do you expect file to be updated with previous day's data?
Thanks,
