### ISSUE TITLE
Stale Data? Symbols/Popularity JSON File Missing Ticker Symbols

### ISSUE THREAD

**Issue by joemccann** [Ameobea/robintrack#90]
The JSON here appears to be stale:

https://ameo.link/u/7n6.json

A search for a new ETF that shows up on Robintrack.net, GERM, is fine:

https://robintrack.net/symbol/GERM

But if you search the JSON file it doesn't exist.

Do you have the latest file somewhere?

Is there an API that is available for all symbols maybe?

Thanks in advance!

**Comment by Ameobea** [comment]
I have no idea where you found that ameo.link link from, in any case that was a one-off and not something that's regularly re-generated.

You can download the full popularity leaderboard as CSV here: ![](https://ameo.link/u/89s.png)

**Comment by joemccann** [comment]
I found that link in the markdown file in the scraper directory:

https://github.com/Ameobea/robintrack/blob/master/scraper/src/RUN_RECOMMENDED_STOCKS_SCRAPER.md

It's the first instruction.

**Comment by Ameobea** [comment]
Ah, I see.  I created the recommended stocks scraper to help out some student researchers; it's not something I will be including in the Robintrack website or making a part of Robintrack officially.

That being said, if you want the exact same file as the one there except updated, you can pull it from here: https://robintrack.net/api/most_popular.json?limit=10000

**Comment by joemccann** [comment]
Yup all good.  I made a utils lib grabbing that file here:  https://github.com/joemccann/robintrack-api-utilities
