### ISSUE TITLE
Data Download on Site Contains Stale (7/18) Data

### ISSUE THREAD

**Issue by babeljeff** [Ameobea/robintrack#91]
Seems as if the data files are still from 7/18.  Perhaps the process isn't running?

Thanks.

I've fixed the data export script and switched it back to tar.gz format.  The link on the data export page is updated and the export should properly run nightly as it has in the past.  If any other issues come up, please let me know!

_Originally posted by @Ameobea in https://github.com/Ameobea/robintrack/issues/89#issuecomment-660546988_

**Comment by Ameobea** [comment]
Hi, I made a silly misconfiguration that caused the script to not run.  I just ran it manually (the script itself works fine) and the data is fresh again.

Ty for letting me know!
