### ISSUE TITLE
Data Download not working on site

### ISSUE THREAD

**Issue by tadbooch** [Ameobea/robintrack#92]
Hi, similar to issue #89, data download seems to have stopped working again. This download link (https://robintrack-data.ameo.design/robintrack-popularity-history.tar.gz) returns file size of 1kb again.

I think it broke again after fixes for #91 (data were stale).

Thanks for looking into it.

**Comment by babeljeff** [comment]
Having same issue... thanks

**Comment by babeljeff** [comment]
worked for me this morning

**Comment by tadbooch** [comment]
same. closing this. thanks
