### ISSUE TITLE
`popularity_history_exporter` Cron job? Website has stale data

### ISSUE THREAD

**Issue by joemccann** [Ameobea/robintrack#94]
It appears the latest popularity download on robintrack.net only has data up til July 8 2020.  

Is there a way we can set this up to have it run the `popularity_history_exporter` daily at the end the day via cron job ( `0 0 * * *` ) and upload to wherever you are hosting the tar file?

**Comment by Ameobea** [comment]
There was a cron job set up, but I had tweaked the script to run the Docker container in interactive terminal mode (`-it`) which broke inside of cron.  I've corrected this, and I've observed the archive correctly generate two nights in a row now so I'm closing this issue but will continue to monitor the archive's generation going forward.
