### ISSUE TITLE
Chart on number of new users vs time

### ISSUE THREAD

**Issue by elwerro** [Ameobea/robintrack#95]
I wanted to know how many new accounts have been made in 2020. Is there a way to keep track of this?

**Comment by ghostwords** [comment]
Related: https://github.com/Ameobea/robintrack/issues/37#issuecomment-429549038

**Comment by Ameobea** [comment]
Robinhood doesn't actually publish any regularly updated metrics about their total number of active accounts, so it isn't possible to provide that data on the website.  I'm working on a feature currently to try to gauge retail trading activity in a different manner, and it will hopefully be available by the end of the week.
