### ISSUE TITLE
More often scrapes

### ISSUE THREAD

**Issue by Xilosof** [Ameobea/robintrack#98]
Can i do more often scrapes?

**Comment by Ameobea** [comment]
The Robinhood API that Robintrack pulls from is public and you're free to pull from it yourself.  I limit Robintrack to hourly for a couple of reasons:

* There is some lag time in the data received from Robinhood, around less than an hour in my testing.  Making more regular pulls will do little to provide value if data doesn't update that reguarly.
* I want to avoid hitting the Robinhood API more than necessary.  It's provided publicly, but there is no documentation about it so I want to avoid making more requests than I need to.

I will not be increasing the frequency of scraping that Robintrack does, but as I mentioned the API endpoint from Robinhood is public so you're free to pull from it yourself.  The full code for doing that is in this repository in the `scraper` sub-directory, so you can use that as a guide if you'd like.

**Comment by Xilosof** [comment]
Can you give me a hint ? Frequency is limited by the scraper or API?

**Comment by Ameobea** [comment]
The Robinhood API endpoint does have a rate limit imposed on it; I keep my scraping spaced out to respect it.  As I said, it's undocumented, so you'll have to find the right spacing to respect it.
